server:
  port: 8001
  shutdown: graceful
  tomcat:
    accept-count: 200
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 300
      min-spare: 20

spring:
  application:
    name: provider
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  datasource:
    url: jdbc:mysql://localhost:3306/provider?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
      ddl-auto: validate
    show-sql: true